version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: student_mongo
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=123
    volumes:
      - mongo-data:/data/db
    restart: "unless-stopped"
volumes:
  mongo-data:
    driver: local